---
driver:
  name: docker
  use_sudo: false
  provision_command: mkdir -p /run/sshd
  network:
    - ["forwarded_port", {guest: 80, host: 2368}]
    - ["forwarded_port", {guest: 2368, host: 2368}]
    - ["forwarded_port", {guest: 8080, host: 2368}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04

verifier:
  name: inspec

suites:
  - name: default
    verifier:
        inspec_tests:
          - test/integration/default
    run_list:
      - recipe[ghost-install]
    attributes:
      # authorization:
      #   sudo:
      #     passwordless: true
      #     include_sudoers_d: true
