sudo: required

notifications:
  email:
    on_success: never
    on_failure: dbalders@gmail.com

addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

install: bundle install

services: docker

env:
  matrix:
  - INSTANCE=ubuntu-1604

script: KITCHEN_LOCAL_YAML=.kitchen.local.yml kitchen verify ${INSTANCE}