Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-16.04"
  c.vm.hostname = "default-ubuntu-1604.vagrantup.com"
  c.vm.network(:forwarded_port, {:guest=>80, :host=>8080})
  c.vm.network(:forwarded_port, {:guest=>2368, :host=>2368})
  c.vm.network(:forwarded_port, {:guest=>2368, :host=>80})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/davidbalderston/.kitchen/cache", "/tmp/omnibus/cache", create: true
  c.vm.provider :virtualbox do |p|
  end
end
